#!/bin/bash

# Exit immediately on errors.
set -e

#
# Project create and install tasks (avoid hacking build:project:create command).
#
function project-tasks() {
 # Generate lando config.
  setup_lando
}



#
# Setup local devleopment environment.
#
function setup_lando() {
  # Check for existing lando files.
  if [[
      ( ! -f ".lando.yml" )
  ]]; then
    echo "📂 💨  Generating Lando configuration file..."
      terminus lando:setup
    echo "✅ Done!"
  fi
  # Check for existing behat config files.
    if [[
        ( ! -f ".behat-lando.yml" )
    ]] && [[
                  ( ! -f ".lando.aliases.drushrc.php" )
              ]]; then
      echo "📂 💨  Generating .behat-lando.yml."
        terminus lando:behat
      echo "✅ Done!"
    fi
}

project-tasks


